question_data = [
        {"category": "Entertainment: Video Games",
         "type": "boolean",
         "difficulty": "hard",
         "question": "The retail disc of Tony Hawk's Pro Skater 5 only comes with the tutorial.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "Han Solo's co-pilot and best friend, 'Chewbacca', is an Ewok.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Rapper Snoop Dogg's real name is 'Cordozar Calvin Broadus, Jr.'.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "'Typewriter' is the longest word that can be typed using only the first row on a QWERTY keyboard.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "hard",
         "question": "Joseph Stalin's real name was Ioseb Bessarionis dze Dzugashvili.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
         "question": "The color of the pills in the Matrix were Blue and Yellow.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Faust is a playable character in 'Guilty Gear Xrd Revelator'.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
         "question": "The 'Squaring the Circle' problem is solvable.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                          "question": "Type 1 diabetes is a result of the liver working improperly.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
         "question": "The binary number '101001101' is equivalent to the Decimal number '334'",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The color orange is named after the fruit.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
         "question": "The card game 'Munchkin' won the 2001 Origins Award for Best Traditional Card Game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "easy",
         "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The 2005 video game 'Call of Duty 2: Big Red One' is not available on PC.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
         "question": "The Angry Video Game Nerd's alter ego is 'Board James'.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "TF2: The Heavy's voice actor, Gary Schwartz, voices the Demoman as well ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "You could walk from Norway to North Korea while only passing through Russia.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Sonic the Hedgehog universe, Tails' real name is Miles Prower.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
                                           "question": "'Cube', 'Cube 2: Hypercube' and 'Cube Zero' were directed by the same person.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "The name of the attack 'Kamehameha' in Dragon Ball Z was named after a famous king of Hawaii.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
         "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
         "question": "Arriva is owned by the Deutsche Bahn.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The names of Tom Nook's cousins in the Animal Crossing franchise are named 'Timmy' and 'Jimmy'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                          "question": "Daft Punk originated in France.", "correct_answer": "True",
                                          "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "David Baszucki was a co-founder of ROBLOX Corporation.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
         "question": "In 'Doctor Who', the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "hard",
                                           "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In 'Call Of Duty: World At War', the first appearance of the 'PPSH-41' in 'Zombies' was in the map 'Der Riese'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "In the 'To Love-Ru' series, Peke is considered a female robot.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Animals", "type": "boolean", "difficulty": "medium",
                                           "question": "Finnish Lapphund dogs were used for herding reindeer.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega's new flagship mascot before Sonic was.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "An episode of 'The Simpsons' is dedicated to Moe Szyslak's bar rag.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
         "question": "The song Scatman's World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Mythology", "type": "boolean", "difficulty": "easy",
         "question": "A wyvern is the same as a dragon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
         "question": "A scalene triangle has two sides of equal length.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "medium",
                                          "question": "The Korean War ended in 1953 without any ceasefire.",
                                          "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The commercial UK channel ITV stands for 'International Television'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "medium",
                                          "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
         "question": "Franz Joseph I was the last emperor of Austria.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                                          "question": "The original ending of 'Little Shop Of Horrors' has the plants taking over the world.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "The mitochondria is the powerhouse of the cell.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Green Day's album 'American Idiot' is considered a 'punk rock opera.'",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]}
]
